## [Resume] Computation on NumPy Arrays: Universal Functions

In the next sections we'll show the reasons of NumPy is so important in the Python in data science. 
See with more details: [Introduction-to-NumPy](https://jakevdp.github.io/PythonDataScienceHandbook/#2.-Introduction-to-NumPy)


Python default implementation is very slowly for loop, but other hand this is part of interpreted languages, different of C, Fortran and Java.

In [4]:
import numpy as np

np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1 , 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

The function above is calculate the [Reciprocal Number](https://www.mathsisfun.com/reciprocal.html) and is very fast for 5 elements and its possible to measure the time with the ```%timeit```

In [5]:
%timeit compute_reciprocals(values)

35.6 µs ± 613 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Awesome isn't? 

So its become a problem or better begging to be very slow with big arrays with size of 1 million

In [7]:
large_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(large_array)

6.21 s ± 73.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Slowly ins't?

Here take almost one minute.

Each time of function ```compute_reciprocals``` is computed Python first examine the object's type and does a dynamic lookup of the correct function to use for that type (remember language interpreted), in compiled code this verification is made before of the code execute become more efficiently.

### Introducing UFuncs

Numpy provides a conveninet interface into just this kind of statically typed, compiled routine this is know as a **vectorized operation**, this can be accomplished by a simply perfoming an operation on the array, which will then be applied to each element. Vectorized approch is designed to push the loop into the compiled layer that underlies NumPy, leading to much faster execution.

Examples:

In [12]:
compute_reciprocals(values) # python loop

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [13]:
(1.0 / values) # vectorized operations same value

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

Now compare with the operations array of 1 million of elements

In [16]:
%timeit (1.0 / large_array)

6.61 ms ± 196 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Amazing, its much faster!! 